# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from enum import Enum

class AgentConfig:
    r"""
    Stores the configuration of the agent and the ghost, if there is one.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Returns the name of the agent.
        """
    @property
    def ghost_policy(self) -> typing.Optional[GhostPolicy]:
        r"""
        Returns the ghost's policy, if there is one.
        """
    @property
    def ghost_penalty(self) -> builtins.int:
        r"""
        Returns the reward applied when the ghost catches the agent.
        """
    @property
    def ghost_occlusion(self) -> builtins.bool:
        r"""
        When true, a ghost hidden behind a wall (i.e., with no line of sight
        from the agent) is not observed for policy look-up purposes. Defaults
        to false. Invalid or hypothetical states where the ghost is inside a
        wall are also treated as hidden.
        """
    @property
    def transition(self) -> builtins.list[builtins.float]:
        r"""
        Returns the probabilities that the agent's actual action are
        [intended, right, back, left]. Entries must be nonnegative and sum to 1.
        """

class Board:
    r"""
    Represents the state of the board.
    Stores the dimensions and board layout.
    """
    @property
    def width(self) -> builtins.int: ...
    @property
    def height(self) -> builtins.int: ...
    @property
    def agent_position(self) -> tuple[builtins.int, builtins.int]: ...
    @property
    def ghost_position(self) -> typing.Optional[tuple[builtins.int, builtins.int]]: ...
    @property
    def goblets(self) -> builtins.list[Goblet]: ...
    @property
    def wall_positions(self) -> builtins.set[tuple[builtins.int, builtins.int]]: ...
    def __getitem__(self, position:tuple[builtins.int, builtins.int]) -> EntityType: ...

class CameraConfig:
    @property
    def scale(self) -> builtins.float: ...

class EntityType:
    class Empty(EntityType):
        __match_args__ = ()
        def __new__(cls) -> EntityType.Empty: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key:builtins.int) -> typing.Any: ...
    
    class Wall(EntityType):
        __match_args__ = ()
        def __new__(cls) -> EntityType.Wall: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key:builtins.int) -> typing.Any: ...
    
    class Goblet(EntityType):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.int: ...
        def __new__(cls, _0:builtins.int) -> EntityType.Goblet: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key:builtins.int) -> typing.Any: ...
    
    class Agent(EntityType):
        __match_args__ = ()
        def __new__(cls) -> EntityType.Agent: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key:builtins.int) -> typing.Any: ...
    
    class Ghost(EntityType):
        __match_args__ = ()
        def __new__(cls) -> EntityType.Ghost: ...
        def __len__(self) -> builtins.int: ...
        def __getitem__(self, key:builtins.int) -> typing.Any: ...
    
    ...

class GGConfig:
    r"""
    Represents the entire configuration of the game.
    """
    @property
    def agent(self) -> AgentConfig: ...
    @property
    def goblets(self) -> GobletConfig: ...
    @property
    def world_generation(self) -> WorldGenerationConfig: ...
    @property
    def camera(self) -> CameraConfig: ...
    @property
    def render_delay_secs(self) -> builtins.float: ...
    @render_delay_secs.setter
    def render_delay_secs(self, value: builtins.float) -> None: ...
    @property
    def generation_seed(self) -> typing.Optional[builtins.int]: ...
    @generation_seed.setter
    def generation_seed(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def episode_seed(self) -> typing.Optional[builtins.int]: ...
    @episode_seed.setter
    def episode_seed(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def debug(self) -> builtins.bool: ...
    @debug.setter
    def debug(self, value: builtins.bool) -> None: ...
    @property
    def headless(self) -> builtins.bool: ...
    @headless.setter
    def headless(self, value: builtins.bool) -> None: ...
    @property
    def world_file(self) -> typing.Optional[builtins.str]:
        r"""
        Path to a YAML world file to load instead of procedurally generating
        a board. When set, `world_generation`'s `world_width`/`world_height`/
        `num_obstacles`/`obstacle_radius_cells` are ignored (the board's
        dimensions/walls/goblets/agent/ghost positions come from the file);
        `world_generation.cell_size` still applies for rendering scale.
        """
    @world_file.setter
    def world_file(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Path to a YAML world file to load instead of procedurally generating
        a board. When set, `world_generation`'s `world_width`/`world_height`/
        `num_obstacles`/`obstacle_radius_cells` are ignored (the board's
        dimensions/walls/goblets/agent/ghost positions come from the file);
        `world_generation.cell_size` still applies for rendering scale.
        """
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None: ...
    @property
    def ghost_policy(self) -> typing.Optional[GhostPolicy]: ...
    @ghost_policy.setter
    def ghost_policy(self, value: typing.Optional[GhostPolicy]) -> None: ...
    @property
    def ghost_penalty(self) -> builtins.int: ...
    @ghost_penalty.setter
    def ghost_penalty(self, value: builtins.int) -> None: ...
    @property
    def ghost_occlusion(self) -> builtins.bool: ...
    @ghost_occlusion.setter
    def ghost_occlusion(self, value: builtins.bool) -> None: ...
    @property
    def transition(self) -> builtins.list[builtins.float]: ...
    @transition.setter
    def transition(self, value: builtins.list[builtins.float]) -> None: ...
    @property
    def scale(self) -> builtins.float: ...
    @scale.setter
    def scale(self, value: builtins.float) -> None: ...
    @property
    def number(self) -> builtins.int: ...
    @number.setter
    def number(self, value: builtins.int) -> None: ...
    @property
    def max_reward(self) -> builtins.int: ...
    @max_reward.setter
    def max_reward(self, value: builtins.int) -> None: ...
    @property
    def world_width(self) -> builtins.float: ...
    @world_width.setter
    def world_width(self, value: builtins.float) -> None: ...
    @property
    def world_height(self) -> builtins.float: ...
    @world_height.setter
    def world_height(self, value: builtins.float) -> None: ...
    @property
    def num_obstacles(self) -> builtins.int: ...
    @num_obstacles.setter
    def num_obstacles(self, value: builtins.int) -> None: ...
    @property
    def obstacle_radius_cells(self) -> builtins.int: ...
    @obstacle_radius_cells.setter
    def obstacle_radius_cells(self, value: builtins.int) -> None: ...
    @property
    def cell_size(self) -> builtins.float: ...
    @cell_size.setter
    def cell_size(self, value: builtins.float) -> None: ...
    @property
    def size(self) -> tuple[builtins.int, builtins.int]:
        r"""
        The size of the board as (width, height) — same as
        `config.world_generation.size`, flattened for convenience. Only
        reflects the *procedurally-generated* size; when `world_file` is
        set, read the actual board size from `GameState.board.width/height`
        instead.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

class GameState:
    r"""
    Represents the game state and holds the bulk of the game logic.
    """
    @property
    def board(self) -> Board:
        r"""
        Returns the state of the board.
        """
    @property
    def reward(self) -> builtins.int:
        r"""
        Represents the immediate reward of the current state. Equals the
        configured ghost penalty if the agent has been caught by the ghost,
        the value of a goblet if the agent has found a goblet, and zero
        otherwise.
        """
    @property
    def done(self) -> builtins.bool:
        r"""
        Returns True if the agent has collected a goblet or has been caught
        by the ghost.
        """
    @property
    def agent_position(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Returns the current position of the agent.
        """
    @property
    def observed_ghost_position(self) -> typing.Optional[tuple[builtins.int, builtins.int]]:
        r"""
        Returns the position of the ghost as observed by the agent. If there is
        no ghost, or if the ghost isn't currently visible (e.g., behind a wall)
        when `ghost_occlusion` is enabled, returns None. Invalid states (e.g.,
        where the ghost is inside a wall) are also treated as hidden.
        """
    @property
    def visible_goblet_positions(self) -> builtins.list[tuple[builtins.int, builtins.int]]:
        r"""
        Returns the positions of goblets visible from the agent's current
        position. Goblets hidden behind walls are omitted.
        """
    @property
    def visible_wall_positions(self) -> builtins.list[tuple[builtins.int, builtins.int]]:
        r"""
        Returns the positions of walls visible from the agent's current
        position. A wall is visible if no other wall lies between the agent
        and that wall.
        """
    def all_states(self) -> builtins.list[GameState]:
        r"""
        Returns a list of `width * height` game states. These are states where
        the agent's position is varied across all positions. If there is a ghost,
        each of these states has the ghost's position fixed at its current one,
        and this function returns an additional `width * height` game states
        where the ghost's position is instead varied across all positions. Note
        that invalid states are not filtered out.
        """
    def next_state(self, action:Action) -> GameState:
        r"""
        Returns the game state that would result from the agent moving in the
        given direction. This move is deterministic, and does not update the
        ghost's position.
        """
    def with_seed(self, seed:builtins.int) -> GameState:
        r"""
        Returns a copy of the current game state with a fixed episode seed,
        used to determine the actions taken by the agent and the ghost.
        """
    def step(self, action:Action) -> GameState:
        r"""
        Returns a new game state resulting from one full environment step.
        This step is not deterministic, and updates both the agent and the
        ghost's position using the episode seed. Fails for the Teleop ghost.
        """
    def reset(self) -> tuple[GameState, builtins.int]:
        r"""
        Returns a new game state set to the original configuration, along with
        its episode seed.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

class Goblet:
    r"""
    Represents the state of a single goblet.
    """
    @property
    def position(self) -> tuple[builtins.int, builtins.int]: ...
    @property
    def reward(self) -> builtins.int: ...

class GobletConfig:
    r"""
    Stores the configuration of all goblets.
    """
    @property
    def number(self) -> builtins.int:
        r"""
        Returns the initial number of goblets.
        """
    @property
    def max_reward(self) -> builtins.int:
        r"""
        Returns the maximum reward of any goblet.
        """

class WorldGenerationConfig:
    r"""
    Stores the configuration of the gridworld.
    """
    @property
    def world_width(self) -> builtins.float: ...
    @property
    def world_height(self) -> builtins.float: ...
    @property
    def num_obstacles(self) -> builtins.int:
        r"""
        Returns the initial number of obstacles.
        """
    @property
    def obstacle_radius_cells(self) -> builtins.int:
        r"""
        Returns the maximum radius of an obstacle in number of cells.
        """
    @property
    def cell_size(self) -> builtins.float: ...
    @property
    def size(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Returns the size of the world as a (width, height) tuple.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

class Action(Enum):
    r"""
    Represents an agent action.
    """
    Up = ...
    Down = ...
    Left = ...
    Right = ...

    @staticmethod
    def from_int(tag:builtins.int) -> Action: ...
    def __reduce__(self) -> tuple[typing.Any, typing.Any]: ...

class GhostPolicy(Enum):
    r"""
    Represents a policy for the ghost.
    """
    Random = ...
    Chaser = ...
    Teleop = ...
    r"""
    The ghost's movement is supplied externally each tick (e.g. by a
    human at the keyboard in the live game) rather than decided
    automatically — see `GameState::step_teleop`. Not usable in headless
    mode (there's no human input to drive it during automated training).
    """

def parse_config(config_path:builtins.str) -> GGConfig: ...

def run(config:GGConfig, policy:typing.Optional[typing.Any]=None, value:typing.Optional[typing.Any]=None) -> typing.Optional[tuple[GameState, builtins.int, builtins.int]]: ...

